name: Compiler APK Kivy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Recuperer le projet
        uses: actions/checkout@v4


      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"


      - name: Installer Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install cython==0.29.34


      - name: Decompresser le projet
        run: |
          mkdir projet
          unzip sql_stock.zip -d projet


      - name: Creer buildozer.spec
        working-directory: projet
        run: |
          buildozer init


      - name: Configurer Buildozer
        working-directory: projet
        run: |

          sed -i \
            's/^title = .*/title = Gestion Vente/' \
            buildozer.spec

          sed -i \
            's/^package.name = .*/package.name = gestionvente/' \
            buildozer.spec

          sed -i \
            's/^package.domain = .*/package.domain = org.gestion/' \
            buildozer.spec

          sed -i \
            's/^requirements = .*/requirements = python3,kivy/' \
            buildozer.spec

          sed -i \
            's/^orientation = .*/orientation = portrait/' \
            buildozer.spec

          sed -i \
            's/^source.include_exts = .*/source.include_exts = py,png,jpg,jpeg,kv,atlas,db,ttf,txt/' \
            buildozer.spec

          echo "android.minapi = 24" >> buildozer.spec

          echo "android.api = 33" >> buildozer.spec

          echo "android.ndk = 25b" >> buildozer.spec


      - name: Afficher la configuration
        working-directory: projet
        run: |
          grep -E \
            "title|package.name|package.domain|requirements|orientation|android.minapi|android.api|android.ndk" \
            buildozer.spec


      - name: Compiler APK
        working-directory: projet
        run: |
          buildozer android debug


      - name: Recuperer APK
        uses: actions/upload-artifact@v4
        with:
          name: gestion-vente-apk
          path: projet/bin/*.apk
          if-no-files-found: error
